### ISSUE TITLE
Logs are always displayed in UTC

### ISSUE THREAD

**Issue by pergolafabio** [TECH7Fox/asterisk-hass-addons#115]
Could it be related to this? I dont see that file either?

https://groups.google.com/g/village-telco-dev/c/Nksc0GNLMDU

![image](https://user-images.githubusercontent.com/43251136/157506706-5e4633e0-4fb8-43ac-a5a8-9b4f47f43fdb.png)

**Comment by felipecrs** [comment]
@pergolafabio I proposed a fix at https://github.com/hassio-addons/addon-debian-base/pull/108. Hopefully it gets merged one day.
