### ISSUE TITLE
Can not install v2.0.2

### ISSUE THREAD

**Issue by sebyldino** [TECH7Fox/asterisk-hass-addons#131]
Hello, 

Failed to install the v2.0.2, get error message:

Can't install ghcr.io/tech7fox/aarch64-addon-asterisk:2.0.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2.0.2&fromImage=ghcr.io%2Ftech7fox%2Faarch64-addon-asterisk&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

**Comment by felipecrs** [comment]
Builds for ARM is still ongoing... wait for this:

https://github.com/TECH7Fox/asterisk-hass-addons/runs/5588226387?check_suite_focus=true
