### ISSUE TITLE
Better config files handling

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/asterisk-hass-addons#134]
Ok. I think what we have currently is not so good. For example, if we make an improvement to one config file, it won't end up being used because the old version from `/config` will be restored.

I have some ideas:

1. Reset config add-on option ([like Cloudflared's one](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#option-reset_cloudflared_files))
2. We can track whether the file got changed or not by the user, like creating a checksums.json list file at `/config/asterisk` to keep track of the original checksum when the file was created. And then, for example, if the file was modified, we don't replace it during initialization, but if it was not modified since its original checksum, we replace it (because it means an upgrade of config file).
3. In case of number 2, we may also replace the modified files but back them up as `.bak` or something.
4. We may be able to improve the auto-generated files handling. For example, we should always name them something like `autogenerated_extensions.conf` and never put them as a file that cannot be replaced by the user like `http.conf`, for example, it should be `autogenerated_http.conf` and then we reference it inside the user customizable `http.conf`
5. Do we really need to modify `asterisk.conf`? If yes, perhaps we should use .patch files instead to make it easier to upgrade during upgrades. Example: we upgraded from Asterisk 18.2 to 18.10 and perhaps some default option was changed in `asterisk.conf` that we never got.

**Comment by felipecrs** [comment]
6. We can create a symlink from `/config/asterisk` to `/etc/asterisk`, by removing the /etc/asterisk completely after copying to /config.

**Comment by nanosonde** [comment]
Nice ideas.

I really would like to see something like this you discribed in 4).
All config things that the addon generated should be put in extra files which can easily identify by some prefix/postfix.

Concerning 5): 
The authors of this addon should know if asterisk.conf needs to be updated in some way or not.
So if the default asterisk.conf from upstream needs to be updated for the user as well, then we should place the new asterisk.conf and rename the old one with some timestamp so that old configs never get overwritten.

**Comment by felipecrs** [comment]
> so that old configs never get overwritten.

Don't you think 2 solves this issue better?

**Comment by felipecrs** [comment]
Like, if user never changed the config by himself, it means that he wants to stick with whatever the default value the addon comes with.

**Comment by felipecrs** [comment]
I have another idea:

We can have two folders in /config:

```
asterisk/reference
asterisk/custom
```

Reference would always be overridden by the files from the container on startup, it would be used as reference by users to write their own configs.

Custom would be a folder with only files that users explicitly customized. If they want to customize, they drag and drop from reference to custom.

This way only the customized files will be retained between upgrades.

What do you guys think?

**Comment by TECH7Fox** [comment]
Will prevent issues like the recent `sip.conf` and `modules.conf` from the chan_sip update.
But maybe call it `asterisk/default` instead of reference?

**Comment by TECH7Fox** [comment]
Thx for your work @felipecrs!
