### ISSUE TITLE
Qualify not working outside LAN

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/asterisk-hass-addons#136]
Like @pergolafabio said, Qualify does not work outside LAN. It registeres and then fails, becoming unreachable.

Previously qualify was disabled. What was the reason it was enabled?

Guessing it's because the contact is local?

```
Added contact 'sip:r6qbhms5@192.168.0.1:4092;transport=ws' to AOR '100' with expiration of 600 seconds
```

Anybody knows a fix for this, or should we just disable it?

**Comment by nanosonde** [comment]
Furthermore the websocket transport is run over TCP so it should not be affected by NAT at all.

**Comment by nanosonde** [comment]
Damn.
The contact line example you provided above is alredy the rewritten one. 

I think it is best to disable it then.

**Comment by pergolafabio** [comment]
not sure if its caused by qualify, its just that strange sip name

for my softphones i also had to disable qualify, if i enable it, the register comes in, and 1 sec later its unreachable

disabled now for my custom extensiosn, and all is fine now

locally all works as expected , just public is an issue

**Comment by nanosonde** [comment]
Qualification is realized by sending SIP OPTIONS requests from the device to asterisk. It is just some basic PING-PONG.
However, it seems that asterisk tries to send the SIP OPTIONS requests to the IP it has from the contact URI.
Normally it should recognize that this a websocket connection and send it over this connection.

This might solve it:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+Configuration_res_pjsip#Asterisk18Configuration_res_pjsip-transport_symmetric_transport

>When a request from a dynamic contact comes in on a transport with this option set to 'yes', the transport name will be saved >and used for subsequent outgoing requests like OPTIONS, NOTIFY and INVITE. It's saved as a contact uri parameter named >'x->ast-txp' and will display with the contact uri in CLI, AMI, and ARI output. On the outgoing request, if a transport wasn't >explicitly set on the endpoint AND the request URI is not a hostname, the saved transport will be used and the 'x-ast-txp' >parameter stripped from the outgoing packet.

Default is "no" for this option.

**Comment by pergolafabio** [comment]
aha, do you think it will also fix it for the softphone/custom extensions? i want to have there a qualify, i need to know when they are offline, so i can send a GCM push message to wake them up

**Comment by TECH7Fox** [comment]
But like you said @nanosonde in the discord, it doesn't make sense for WSS so we should just disable it right?

**Comment by nanosonde** [comment]
> But like you said @nanosonde in the discord, it doesn't make sense for WSS so we should just disable it right?

Yes.

**Comment by pergolafabio** [comment]
Hey @nanosonde . I upgraded to new version, but still my wss clients are unable to register... Where is that strange from address coming from? 

```
[Mar 19 07:17:14] ERROR[689]: res_http_websocket.c:567 ws_safe_read: Error reading from web socket: Success
[Mar 19 07:17:14]     -- Removed contact 'sip:8qpfg9ug@192.168.0.1:41756;transport=ws' from AOR '100' due to shutdown
[Mar 19 07:17:14]   == WebSocket connection from '192.168.0.1:41756' closed
[Mar 19 07:17:14]   == Contact 100/sip:8qpfg9ug@192.168.0.1:41756;transport=ws has been deleted
[Mar 19 07:17:14]   == Endpoint 100 is now Unreachable
```


I have just setup  port forwarding on my 192.168.0.1 router , like external port 9988 to internal 8089... Like I did before on chansip..

Also for my softphones on custom extensions, I can register , I do the same , like external port 9977 to internal  
 5060...
They register fine, but I can't make calls...

If I test all local, it's all fine...

But now that I'm writing this down, I don't think I have configured nat=yes and localnet setup in the pjsip config...

Could that be the issue? Allthough I don't remember me this doing on chan_sip either...

**Comment by TECH7Fox** [comment]
I now see that TLS is set on port 5061. [Link](https://github.com/TECH7Fox/asterisk-hass-addons/blob/main/asterisk/rootfs/etc/asterisk/pjsip.conf#L14)

Could that be the problem?

**Comment by nanosonde** [comment]
SIP over encrypted TCP(a.k.a. TLS) is using default 5061.
5060 is already used by UDP and unencrypted TCP.
SIP over TLS has nothing to do with secure SIP-over-websockets (WSS).
The TLS layer is handled by the HTTP server part of asterisk.

**Comment by nanosonde** [comment]
Working with NAT and SIP can be difficult to setup properly.
You seem to have the signaling part partly right so far when you register successfully.
However, there is more.
Asterisk needs to know what IP addresses it should use in SDP for the media streams as well. When we are talking to about WebRTC, the browser will generate a SDP for the SIP-client. So it all depends on the network topology used. This sometimes complex stuff.

**Comment by nanosonde** [comment]
I recommend to do some SIP packet sniffing in asterisk.

For all unencrypted SIP traffic on UDP/TCP port 5060 you could use this command in the SSH terminal with protection mode disabled:
`docker exec -it addon_b35499aa_asterisk sipgrep`

To enable showing the SIP packets from within asterisk use this:
1) Start asterisk CLI: ` docker exec -it addon_b35499aa_asterisk asterisk -rvvvvvvvvddddddd`
2) Then run this: `pjsip set logger on`

You will now see the actual SIP packets transmitted and received.
Intersting are the INVITE packets that contain the SDPs.
Here you can see the IP addresses that are offered to the remote peer where the mediastreams via RTP are expected.

**Comment by pergolafabio** [comment]
Yes , will do that later for the websocket and the softphone... Don't get ir, it was so easy with chansip...
Just create extension, opened port 5060 and done...
No nat, no external IP settings, no local_net, it just worked with all default settings..

Verry stranger that registration works, but just cant dial the extensions...

**Comment by pergolafabio** [comment]
i think also we need to reverse the qualify frequency in the websockets, it could be usefull
because if HA is closed, it should go to the "unregistered" state...

this could ve verry usefull, because you can configure in the diaplan like =>
if state extension = unregistered => send webhook/push (open HA) app => wait x seconds => dial again

then we dont need that conference

**Comment by nanosonde** [comment]
What happens if the websocket is closed? 
Is the endpoint still shown available?

**Comment by pergolafabio** [comment]
yes indeed, when i tested earlier with chan_sip, same as with custom extensions

**Comment by pergolafabio** [comment]
created  a quick log, from softphone, will do websoclet later, you see first a correct invite for 6001 , same for 6000


```
<--- Received SIP request (849 bytes) from UDP:167.99.119.244:59773 --->
REGISTER sip:myexternal.domain.com:9988 SIP/2.0
Via: SIP/2.0/UDP 99.99.4.3:59773;branch=z9hG4bKp0UiYlBmJkWjFWv6;rport
Contact: <sip:6001@99.99.4.3:59773;rinstance=11C45C2D>;expires=600
Max-Forwards: 70
From: <sip:6001@myexternal.domain.com:9988>;tag=607AE7AEB2255B8BD8E1923AC45FE7E4
Allow: ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, REFER
Supported: replaces, path
To: <sip:6001@myexternal.domain.com:9988>
Expires: 600
Call-ID: 4BE9F520EC3EC8791BB06F53C7C8013ACB9E15B2
CSeq: 2 REGISTER
Authorization: Digest username="6001",realm="asterisk",algorithm=md5,uri="sip:myexternal.domain.com:9988",nonce="1647692386/0ac9f918808d5cc51b5d3a7aa9399ee4",opaque="5ec8ca635823b651",qop=auth,cnonce="YjXKYp2Pn7A8NyWOqQ5zKNDV",nc=00000001,response="fcb2e34be384b9bed3cd10b0626d8d59"
User-Agent: Acrobits SIPIS
Content-Length: 0


    -- Added contact 'sip:6001@99.99.4.3:59773;rinstance=11C45C2D' to AOR '6001' with expiration of 600 seconds
  == Endpoint 6001 is now Reachable
<--- Transmitting SIP response (506 bytes) to UDP:167.99.119.244:59773 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 99.99.4.3:59773;rport=59773;received=167.99.119.244;branch=z9hG4bKp0UiYlBmJkWjFWv6
Call-ID: 4BE9F520EC3EC8791BB06F53C7C8013ACB9E15B2
From: <sip:6001@myexternal.domain.com>;tag=607AE7AEB2255B8BD8E1923AC45FE7E4
To: <sip:6001@myexternal.domain.com>;tag=z9hG4bKp0UiYlBmJkWjFWv6
CSeq: 2 REGISTER
Date: Sat, 19 Mar 2022 12:19:46 GMT
Contact: <sip:6001@99.99.4.3:59773;rinstance=11C45C2D>;expires=599
Expires: 600
Server: Asterisk PBX 18.10.1
Content-Length:  0

```
Then i dial from 6000 to 6001 , i see a correct invite , but 6001 never rings, seems its just unreachable, no error or anything
if i also enable qualify, i see extension going immediately in unregistered state after 0,1 sec after registering

no idea whats wrong..


```
<--- Transmitting SIP request (1269 bytes) to UDP:99.99.4.3:59773 --->
INVITE sip:6001@99.99.4.3:59773;rinstance=11C45C2D SIP/2.0
Via: SIP/2.0/UDP 192.168.0.17:5060;rport;branch=z9hG4bKPj81a6e5e1-161d-4bb7-9fec-864dcc0c5158
From: <sip:6000@192.168.0.17>;tag=8864b9e0-2e5d-452c-92ec-7bba2fc50810
To: <sip:6001@99.99.4.3;rinstance=11C45C2D>
Contact: <sip:asterisk@192.168.0.17:5060>
Call-ID: 644bc8aa-6f43-420a-8293-4106c5fc92af
CSeq: 10012 INVITE
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub, histinfo
Session-Expires: 1800
Min-SE: 90
Max-Forwards: 70
User-Agent: Asterisk PBX 18.10.1
Content-Type: application/sdp
Content-Length:   575

v=0
o=- 1497217351 1497217351 IN IP4 192.168.0.17
s=Asterisk
c=IN IP4 192.168.0.17
t=0 0
m=audio 10218 RTP/AVP 0 8 110 3 111 4 9 107 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:110 speex/8000
a=rtpmap:3 GSM/8000
a=rtpmap:111 G726-32/8000
a=rtpmap:4 G723/8000
a=rtpmap:9 G722/8000
a=rtpmap:107 opus/48000/2
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:60
a=sendrecv
m=video 10718 RTP/AVP 99 100 108
a=rtpmap:99 H264/90000
a=fmtp:99 profile-level-id=42801F
a=rtpmap:100 VP8/90000
a=rtpmap:108 VP9/90000
a=sendrecv
```

**Comment by pergolafabio** [comment]
gonna try later with changing port forwarding now i have like on my router 9988 external to 5060 internal
maybe thats causing issues, normally it shouldnt , it worked before

**Comment by pergolafabio** [comment]
when i enable qualify on the softphones, i see this:

```
[Mar 18 14:50:18]     -- Added contact 'sip:6000@100.70.xx.xx:39538;transport=udp' to AOR '6000' with expiration of 3600 seconds
[Mar 18 14:50:21]     -- Contact 6000/sip:6000@100.70.xx.xx:39538;transport=udp is now Unreachable.  RTT: 0.000 msec
```

**Comment by TECH7Fox** [comment]
Maybe the problem is directmedia? It was off for chan_sip, and the default is on.

**Comment by pergolafabio** [comment]
I can test that later on softphone

**Comment by pergolafabio** [comment]
doesnt help for me

i did a trace now, with qualify enabled for softphone

you see it going in a unrechable state immediately after register, i have no clue why, just setup a port formward like always... seems the endpoints are just not reachable , and i dont know why

i have now 9988 external, to internal 5060 , but i tried also 5060 external, doesnt make any difference

```
<--- Received SIP request (918 bytes) from UDP:46.178.123.20:43101 --->
REGISTER sip:mydomain.com:9988 SIP/2.0
Via: SIP/2.0/UDP xx.xx.56.164:49328;branch=z9hG4bK.dM8EZO4HI;rport
From: <sip:6000@mydomain.com>;tag=IpyVn8SkC
To: sip:6000@mydomain.com
CSeq: 22 REGISTER
Call-ID: ~eFLOlc-y0
Max-Forwards: 70
Supported: replaces, outbound
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: <sip:6000@xx.xx.56.164:49328;transport=udp>;+sip.instance="<urn:uuid:dc2169e5-5870-4374-8d64-1cdb1c9efc6b>"
Expires: 3600
User-Agent: LinphoneAndroid/2.1.730 (belle-sip/1.6.3)
Authorization:  Digest realm="asterisk", nonce="1647760706/05dc007201286ec518c7a14a49396c1a", algorithm=md5, opaque="3c55d6626015d2b9", username="6000",  uri="sip:mydomain.com:9988", response="ac0c25763b36d566a25f3f14e0cfe777", cnonce="dviSErGD4JvzitLz", nc=00000002, qop=auth


<--- Transmitting SIP response (466 bytes) to UDP:46.178.123.20:43101 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP xx.xx.56.164:49328;rport=43101;received=46.178.123.20;branch=z9hG4bK.dM8EZO4HI
Call-ID: ~eFLOlc-y0
From: <sip:6000@mydomain.com>;tag=IpyVn8SkC
To: <sip:6000@mydomain.com>;tag=z9hG4bK.dM8EZO4HI
CSeq: 22 REGISTER
Date: Sun, 20 Mar 2022 07:18:27 GMT
Contact: <sip:6000@xx.xx.56.164:49328;transport=udp>;expires=3599
Expires: 3600
Server: Asterisk PBX 18.10.1
Content-Length:  0


<--- Transmitting SIP request (438 bytes) to UDP:xx.xx.56.164:49328 --->
OPTIONS sip:6000@xx.xx.56.164:49328;transport=udp SIP/2.0
Via: SIP/2.0/UDP 192.168.0.17:5060;rport;branch=z9hG4bKPj5f371335-439f-44e0-a45b-2aa314e2a28e
From: <sip:6000@192.168.0.17>;tag=aef224ab-ae59-4bef-bee2-db8868f41e0b
To: <sip:6000@xx.xx.56.164>
Contact: <sip:6000@192.168.0.17:5060>
Call-ID: b001df05-ca5e-4d3f-81e5-4ca81d72a506
CSeq: 31939 OPTIONS
Max-Forwards: 70
User-Agent: Asterisk PBX 18.10.1
Content-Length:  0


    -- Contact 6000/sip:6000@xx.xx.56.164:49328;transport=udp is now Unreachable.  RTT: 0.000 msec
<--- Transmitting SIP request (438 bytes) to UDP:xx.xx.56.164:49328 --->
OPTIONS sip:6000@xx.xx.56.164:49328;transport=udp SIP/2.0
Via: SIP/2.0/UDP 192.168.0.17:5060;rport;branch=z9hG4bKPj5f371335-439f-44e0-a45b-2aa314e2a28e
From: <sip:6000@192.168.0.17>;tag=aef224ab-ae59-4bef-bee2-db8868f41e0b
To: <sip:6000@xx.xx.56.164>
Contact: <sip:6000@192.168.0.17:5060>
Call-ID: b001df05-ca5e-4d3f-81e5-4ca81d72a506
CSeq: 31939 OPTIONS
Max-Forwards: 70
User-Agent: Asterisk PBX 18.10.1
Content-Length:  0
```

**Comment by pergolafabio** [comment]
What i notice, i see the register coming in from:

sip:6000@xx.xx.56.164:49328

that looks normal
when its registered, it sends back an options pack (qualify)
To: <sip:6000@xx.xx.56.164>

but the port is missing there? is that normal? that must be the reason why its unable to reach the contact

**Comment by pergolafabio** [comment]
aha, found it

added those 2

```
force_rport = yes
rewrite_contact = yes
```

working now, !!! finally

can be closed :-)

but i think we should revert the qualify on the wss extensions, could be verry usefull

**Comment by TECH7Fox** [comment]
I thought because wss is TCP quality isn't needed.

Great you found it! Will add that to the generated extensions.

**Comment by pergolafabio** [comment]
these ones are important:

not 100% sure about rport

```
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no
```

https://community.asterisk.org/t/chan-sip-to-pjsipsoftphones-immediate-go-unreachable-when-on-mobile-if-qualify-is-enabled/92011/4

**Comment by TECH7Fox** [comment]
rport is enabled by default. Also, for webrtc we also need to set a stunaddress. Think I will just include rtp.conf with a google stun server set.

**Comment by pergolafabio** [comment]
How come this was not needed before on chan_sip?

I have posted on discord, still my issue with the card as undefined , any idea

**Comment by TECH7Fox** [comment]
> How come this was not needed before on chan_sip?

No idea. Think some default settings were different.

You got the card issue fixed right, by adding name?
