### ISSUE TITLE
extentions for home assistant persons are not created

### ISSUE THREAD

**Issue by ashwin2101** [TECH7Fox/asterisk-hass-addons#147]
extentions for home assistant persons are not created
I can't find any sensor.asterisk_extension_  
I have rebooted everything

**This my config:**

video_support: false
auto_add: true
generate_ssl_cert: false
certfile: fullchain.pem
keyfile: privkey.pem
mailbox: false
mailbox_port: 12345
mailbox_extension: '100'
log_level: notice
ami_password: ***SECRET***

**Comment by TECH7Fox** [comment]
For the sensors you need the [Asterisk integration](https://github.com/TECH7Fox/asterisk-hass-integration). You can check every extension it creates in `/config/asterisk/pjsip_default.conf`.

**Comment by TECH7Fox** [comment]
Will close now. Let me know if you are still having this problem.
