### ISSUE TITLE
Reload extensions and reload dialplan services

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/asterisk-hass-addons#148]
Will add a service to copy pjsip_custom and pjsip, and reload pjsip module. And a service that copies extensions.conf and reload dialplan.

Think this will be nice to have. If you are debugging something and change the extensions or dialplan a lot,  it will take max 1 second instead of a couple minutes to restart the add-on.

Just making this issue so I don't forget, and if someone has any idea's, now's your chance. :)

**Comment by TECH7Fox** [comment]
Nevermind doesn't seem possible to create services from add-ons. Thought it was for some reason.

Maybe via the integration.

**Comment by felipecrs** [comment]
It's also not complicated to create a HA script which calls the stdin service from SSH terminal to run a docker exec call to reload the asterisk extensions.

**Comment by TECH7Fox** [comment]
Looked at that as well, but they removed the stin service.

**Comment by TECH7Fox** [comment]
Nevermind, stupid of me. It was only a changelog for the SSH add-on. My bad.

**Comment by felipecrs** [comment]
I have one other idea to tackle this issue in a more simpler way:

Instead of copying custom files over the default files (rsync), we could instead create add symbolic links into /etc/asterisk that points to the custom files in /config/asterisk/custom.

Then, the users can reload things by calling the Asterisk CLI commands directly.

The only drawback is that, if the user adds a new file, then for that file to be picked up it would still be required to restart the add-on, but I think this is an Ok compromise.

**Comment by felipecrs** [comment]
I can work on it if agreed. Any opinions?

**Comment by felipecrs** [comment]
It's even possible to create a service that keeps watching the /config/asterisk/custom directory for file added/removed and then properly create/delete the symlinks on the fly. But honestly I don't think it's worth it... adding/deleting files is not something you do regularly, thus restarting the add-on for such should be acceptable.

**Comment by TECH7Fox** [comment]
> But honestly I don't think it's worth it...

I agree, the add-on restarts much quicker for me now then before and like you said changing the config is not something people do very often.
Maybe we can skip this feature.

**Comment by TECH7Fox** [comment]
And indeed it's also possible with the SSH add-on when we use symlinks.

**Comment by felipecrs** [comment]
- https://github.com/TECH7Fox/asterisk-hass-addons/pull/166
