### ISSUE TITLE
Enable PJSIP

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/asterisk-hass-addons#17]
Load the pjsip module, test and resolve issues with chan_sip.

And maybe even migrate the websocket extensions (from auto_add) to pjsip?

**Comment by felipecrs** [comment]
Ref: https://wiki.asterisk.org/wiki/display/AST/Migrating+from+chan_sip+to+res_pjsip

**Comment by felipecrs** [comment]
I think this is becoming more and more important, every time I search internet about an error found, it's mentioned "why are you using chan_ship instead of pjsip? blah blah blah".

**Comment by TECH7Fox** [comment]
I agree, will test pjsip with wss when I get a chance.

**Comment by TECH7Fox** [comment]
Awesome work! :)
