### ISSUE TITLE
Add RTSP_SIP

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/asterisk-hass-addons#173]
Add [https://github.com/tommyjlong/app_rtsp_sip](RTSP_SIP) to the Asterisk build.

**Comment by pergolafabio** [comment]
Code needs a few changes, I'll post later

**Comment by pergolafabio** [comment]
hey @TECH7Fox 

In dockerfile i added this below, right before the compilation of asterisk:

```
## Install app_rtsp_sip
WORKDIR /usr/src/asterisk
COPY patches/rtsp_sip_links.sh /usr/src/asterisk
RUN ./rtsp_sip_links.sh
COPY patches/app_rtsp_sip.c /usr/src/asterisk/apps
```

For the 2 files, grab the ones from my github : https://github.com/pergolafabio/app_rtsp_sip
in the .sh file i removed the sudo commands, sudo doesnt work on your addon
in the .c file, i removed the "CheckHeaderValue" function, its not needed, can give issues

maybe you can include it in the 2.3.0 release? 

anyway, you can use this dialplan to  watch an rtsp stream:

```
exten => 1,1,Answer()
 same => n,RTSP-SIP(rtsp://admin:XXXX@192.168.0.70:554/Streaming/Channels/102,0,Hikvision,5060)
```
