### ISSUE TITLE
please include module chan_sip (and dependant for sip) at add-on

### ISSUE THREAD

**Issue by VitalyIak** [TECH7Fox/asterisk-hass-addons#185]
Unfortunatelly it's not possible to use chan_sip module (pjsip doesn't work correct with my doorbell as outbound registratiion, with chan_sip (asterisk 13 works ok)
By the way - do you know that Dahua VTO doesn't manage Mifare cards for access, when you switch to external SIP server. Any solutions? As i understand it's possible to use internal VTO's SIP server and use outbound registration from asterisk, but pjsip works strange at all... ((

**Comment by felipecrs** [comment]
I think this is reasonable. I also identified an issue with pjsip and Dahua, which I posted in the Discord chat some months ago.

**Comment by TECH7Fox** [comment]
We removed chan_sip as it is depreciated and can give conflicts with pjsip. pjsip only works different on the background and has different settings. It should work with all pjsip devices. Did you try this: [from the doorbells-general channel on discord](https://discord.com/channels/912636682346582076/927580630735261707/968106039520149544)

And for the [rfid issue](https://discord.com/channels/912636682346582076/927580630735261707/1011303528549056582).

**Comment by VitalyIak** [comment]
I'm new at discord and unable to access this channel, unfortunately...  links are useless without invitation to channel, as I understand. My discord id is ratnet#7706, please help to join this channel. Thanks in advance!

**Comment by VitalyIak** [comment]
> And for the [rfid issue](https://discord.com/channels/912636682346582076/927580630735261707/1011303528549056582).

Thanks for workaround, but this workaround only for add RFID cards, it's totally impossible to manage - delete and view current set of cards, unfortunately.

**Comment by TECH7Fox** [comment]
>  it's totally impossible to manage - delete and view current set of cards

Also not on Home Assistant with the dahua integration?

**Comment by VitalyIak** [comment]
> Also not on Home Assistant with the dahua integration?
Yes, unfortunatelly there is no options to manage RFID cards in case of external SIP server.
I suppose - may be it's possible to export/import settings and manually change information about cards, but it's very uncomfortable workaround. 
Concern PJSIP+Dahua i can conclude following things:
for succesfull and right registration it's mandatory to use **contact_user=9901#0** at registration
[9901]
type=registration
transport=transport-udp
outbound_auth=9901
server_uri=sip:192.168.1.30:5060
client_uri=sip:9901#0@192.168.1.30:5060
retry_interval=60
contact_user=9901#0

but, there is a bug at Dahua firmware and call from SIP via asterisk with PJSIP it's impossible to perform because:
asterisk reports error: 
**No joint capabilities for 'audio' media stream between our configuration((ulaw)) and incoming SDP((h264))**
this problem reproduced, because Dahua VTO panel at SDP packets provide video information before aodio, and asterisk developers said that it's a problem... But Dahua doesn't hurry up to fix it )))
more info - [here](https://community.asterisk.org/t/video-works-when-a-calls-b-not-when-b-calls-a/68375) 
Just for information and your consideration. I'll try to use flexisip and freeswitch instead of asterisk...

**Comment by E-NINA** [comment]
Hello, I'm exactly on the same situation, I've a VTO's alreday configured to connect with PJSIP but due the issue already mentioned by VitalyIak, I can't get video from doorbell. With legacy SIP it works, it will be really helpfull to have at least the possibility to enable legacy SIP.

**Comment by felipecrs** [comment]
I have zero experience with the Asterisk code base, but if someone can come up with a patch for making pjsip work with VTO, we can add the patch to tha add-on.

**Comment by banny310** [comment]
@TECH7Fox @felipecrs Is there any possibility to have Dahua VTO doorbell working with video (both ways call A->B and B->A) with asterisk as client or server to Dahua. If yes could you post some configuration how to do it? 
I have try many ways with addon: 
- VTO to Asterisk (type: endpoint)
- Asterisk to VTO (type: registration)
Still no luck with video from VTO at all. 
Everything works (including video) between ha-card, linphone or microsip.

**Comment by bdherouville** [comment]
I totally agree as it would help to make Dahua VTO compatible. See explanations [https://ipcamtalk.com/threads/dahua-ip-intercom-vto3211d-p2-new-p-p4-door-station-experience-review-firmware-support.26820/post-470664](url)

chan_sip configuration files are present in the asterix folder tree of the module.
Why not setting a default configuration file for chan_sip with different ports (5260 for example) and adding the module chan_sip.so to the add-on BUT disabling it in modules.conf ?

It would be enabled manually.

**Comment by felipecrs** [comment]
Yes, this is doable and also acceptable. PRs are welcome.

**Comment by bdherouville** [comment]
I can work on the sip.conf file but I don't know how to enable sip module into the add-on.

**Comment by felipecrs** [comment]
You can get inspiration from this:

- https://github.com/TECH7Fox/asterisk-hass-addons/pull/112

**Comment by felipecrs** [comment]
After upgrading Asterisk to 20, add-on version 2.3.4, everything seems to be working with my VTO using PJSIP. Can someone else please verify?

https://github.com/TECH7Fox/asterisk-hass-addons/pull/199#issuecomment-1360463374

**Comment by bdherouville** [comment]
> After upgrading Asterisk to 20, add-on version 2.3.4, everything seems to be working with my VTO using PJSIP. Can someone else please also confirm?
> 
> https://github.com/TECH7Fox/asterisk-hass-addons/pull/199#issuecomment-1360463374

Glad to hear that.
Can you share your doorbell model and your firmware version?

**Comment by felipecrs** [comment]
[VTO2202F-P-S2](https://www.dahuasecurity.com/products/productDetail/60597?from=rss)
V4.600.0000000.0.R.220813

Do not [change the codec using the ONVIF method](https://github.com/blakeblackshear/frigate/discussions/2572), otherwise it will not work. If you did, just do a factory reset.

**Comment by bdherouville** [comment]
> [VTO2202F-P-S2](https://www.dahuasecurity.com/products/productDetail/60597?from=rss) V4.600.0000000.0.R.220813
> 
> Do not [change the codec using the ONVIF method](https://github.com/blakeblackshear/frigate/discussions/2572), otherwise it will not work. If you did, just do a factory reset.

Even by starting by a brand new firmware installation it does not work. I start to think that my model has something special.

**Comment by felipecrs** [comment]
If you want to try with chan_sip, clone the repository in your /addons folder, and do a `git checkout v1.3.3`.

**Comment by bdherouville** [comment]
Thank you, in the mean time I opened a ticket to dahua support.

**Comment by felipecrs** [comment]
Closing this since VTOs now appears to work with Asterisk 20. Tested by me and @bdherouville. If someone else face issues, let us know.

**Comment by Condorello** [comment]
:(
It's 2 week or 3 now since i'm trying to make my VTO working. It's a old one... vto2111d first generation and works fine on freepbx with chansip and and also pjsip (asterisk 13). When moved the same configuration on latest addon i can see video but no audio is passing (local, no nat). I've also tried every config, the wiki one, the discord one etc. Video ok but no audio :(

I thinks it could be usefull add chan_sip on another port for who has a old dahua device.

**Comment by felipecrs** [comment]
Maybe you should also report this issue to Asterisk.
