### ISSUE TITLE
help please cannot login ami

### ISSUE THREAD

**Issue by art1469** [TECH7Fox/asterisk-hass-addons#196]
Because I use different ip not same but config only permit 127.0.0.1 and u add-on only use admin  can i change user or how to make admit can permit 2 ip   

127.0.0.1
192.168.0.0

Help Please

**Comment by TECH7Fox** [comment]
How is it a different IP? Do you have 2 seperate Home Assistant servers?
I never even considered this and it's not possible right now because the config get's overwritten.

**Comment by felipecrs** [comment]
Closing due to lack of response.
