### ISSUE TITLE
custom pjsip and rtp port

### ISSUE THREAD

**Issue by Condorello** [TECH7Fox/asterisk-hass-addons#202]
Hi, i left openend the Port 5060 in my router and (as prrevidible) today my logs are full of login attempts.
it's possibile to add the possibility to choose the sip and RTP Ports in the configuration Page?
Currently i solved by manually changing pjsip.default and RTP.conf.

**Comment by felipecrs** [comment]
> Currently i solved by manually changing pjsip.default and RTP.conf.

This is the way to go.

Now, just wondering, can't you simply close the port on your router?

**Comment by TECH7Fox** [comment]
> it's possibile to add the possibility to choose the sip and RTP Ports in the configuration Page?

It's not possible to put a port range in the configuration page. And now I'm thinking abou it, does Asterisk still work if you change the ports like that? If Asterisk sends the ports for the call when dialing, it won't work right?

**Comment by felipecrs** [comment]
But that's not the case anyway because the add-on uses host network, which means no port-forwarding from the add-on configuration will make any difference. The port has to be changed from the Asterisk configuration and not from the add-on configuration.

**Comment by Condorello** [comment]
Thanks for your attention. Since i changed the Port the attacks stopped, and it's known that there are bot which Always Scan 24h/24 for sip service on the common port 5050 and 5061. The Port must be forwarded, otherwise external client (linphone android/iOS) cannot connect, and it's impossible to use another Port outside on the wan and redirect on the 5060 because in this case the client cannot connect on local network (they are trying to connect to the outsider Port which Is not where asterisk Is running inside).
IMHO The asterisk Port, at least, should be configurabile from gui.
