### ISSUE TITLE
Refactor app_rtsp_sip install logic

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/asterisk-hass-addons#203]
We should clone it from its GitHub repo like we do for everything else instead of adding the whole file in our repo.

If patches are required, we should patch them using a patch file, like we also do for everything else.

@TECH7Fox do you remember if you took the file unaltered, or actually altered it? I did a quick VS Code diff comparing to https://github.com/tommyjlong/app_rtsp_sip and I found these diffs:

![image](https://user-images.githubusercontent.com/29582865/212554243-57f5a2c8-f9c8-435f-b076-583bdaa25f29.png)

If you made these changes, I suppose they should be kept. Right?

**Comment by felipecrs** [comment]
Never mind, I just found out that they should be taken from this repo instead: https://github.com/pergolafabio/app_rtsp_sip

**Comment by tommyjlong** [comment]
Is pergolafabio going to be the maintainer?

**Comment by felipecrs** [comment]
@tommyjlong, in fact I took the changes from @pergolafabio, created a git patch and I'm using your original repo + this patch instead of taking from @pergolafabio's fork.

@pergolafabio if you have no plans to maintain it, and the only consumer was this add-on, you can safely delete your fork if you wish.

**Comment by pergolafabio** [comment]
Yeah, I removed that checkheader , cause it gave issues on Hikvision camera's

**Comment by tommyjlong** [comment]
OK thanks guys.  Just wanted to know how to think about it in the future if I start making changes to it on my side. 
FYI, I had to rebuild a new HA system over the holidays, and I decided to start using this Add-on :)

**Comment by pergolafabio** [comment]
Welcome aboard :-)
