### ISSUE TITLE
Cant Install Addons

### ISSUE THREAD

**Issue by radoprajitno** [TECH7Fox/asterisk-hass-addons#238]
Hi.
I'm migrating my HomeAssistant Installation from a VirtualBox enviroment to HAOS on Proxmox VE (Also HAOS)
I'm migrating it manually, installing Add-ons and cards 1 by 1.

I somehow can't install the Asterisk Hass Addons, 

It shows on the system log:

> Logger: homeassistant.components.hassio
> Source: components/hassio/websocket_api.py:125
> Integration: Home Assistant Supervisor
> First occurred: 7:54:54 PM (2 occurrences)
> Last logged: 8:46:47 PM
> 
> Failed to to call /addons/3e533915_asterisk/install - Can't install ghcr.io/tech7fox/asterisk-hass-addon:4.0.2: 404 Client Error for http+docker://localhost/v1.41/images/ghcr.io/tech7fox/asterisk-hass-addon:4.0.2/json: Not Found ("no such image: ghcr.io/tech7fox/asterisk-hass-addon:4.0.2: No such image: ghcr.io/tech7fox/asterisk-hass-addon:4.0.2")

thanks before

**Comment by felipecrs** [comment]
Try `docker pull ghcr.io/tech7fox/asterisk-hass-addon:4.0.2` (with the SSH community add-on with protection mode disabled), and see what happens.

I know nothing about Proxmox itself.

**Comment by felipecrs** [comment]
Not sure as well. If I find something will post here.

**Comment by radoprajitno** [comment]
thanks @felipecrs

**Comment by felipecrs** [comment]
Can you try again? I rebuilt the 4.0.2 and pushed. I don't know what was wrong, but please try again.

**Comment by radoprajitno** [comment]
@felipecrs 

Now it works! XD

**Comment by felipecrs** [comment]
Funny 😅
