### ISSUE TITLE
Default STUN server timeout in local network

### ISSUE THREAD

**Issue by ernst77** [TECH7Fox/asterisk-hass-addons#241]
Hello,

I've noticed that by default we have `rtp.conf` file with:

```

[general]
rtpstart=10000
rtpend=20000
icesupport=yes
stunaddr=stun.l.google.com:19302
```

The network for my SIP and asterisk does not have internet access, it's all internal so STUN request all timeout.

Thus by default the call start safter `6 sec` when attempt to reach stun server times out.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/17262977/229787039-bcf2c1f1-13af-4e7a-9ef5-4be033d46edc.png">

Do we really need the line `stunaddr=stun.l.google.com:19302` in `rtp.conf` ?

**Comment by felipecrs** [comment]
@ernst77, I believe this setting is helpful to reduce configuration for the majority of the users which have internet access on their Asterisk instance.

I have no personal preference however on what should be the default, as I don't use this feature.

You can of course customize this file as you want, to remove such file.

As this issue received no feedback from other people, I'm tempted to close it. But I will wait a few more days.
