### ISSUE TITLE
Addon DNS

### ISSUE THREAD

**Issue by Danny89530** [TECH7Fox/asterisk-hass-addons#268]
Hi @TECH7Fox,
I am trying to configure the Asterisk addon in order to set up the trunk for Telecom Italia's VoIP service.

Everything seems to be working, as long as I manually modify the resolv.conf file inside the addon's shell, inserting Telecom's DNS.

On my HomeAssistant instance, I already have the AdGuard addon installed for some time. However, it seems to be completely ignored, as I still see the addon pointing to the server's IP instead of the container's IP.

What am I doing wrong?

Thank you in advance.

**Comment by felipecrs** [comment]
AFAIK AdGuard add-on isn't taken into account as DNS server for other add-ons.

One thing you can try to do is to set the DNS in the Asterisk config files:

https://wiki.asterisk.org/wiki/display/AST/Asterisk+20+Configuration_res_resolver_unbound

```ini
; /config/asterisk/custom/resolver_unbound.conf

[general]
nameserver = 127.0.0.1@53
resolv =
```

Theoretically it should make Asterisk use your AdGuard home as DNS server.

**Comment by Danny89530** [comment]
Hi @felipecrs,

Thank you for your response. Based on the various tests I have conducted, it seems that the module allowing the use of that specific configuration has not been compiled into the Docker image of the addon.

In reality, my hope was that it could be implemented in the future so that we can manually insert a custom DNS configuration.

**Comment by felipecrs** [comment]
Hm... that could be the case. PRs are welcome if you happen to figure it out.

**Comment by Danny89530** [comment]
I have just submitted the PR #270 
I have tested it now without any issues, and I hope you can integrate it soon!

**Comment by felipecrs** [comment]
Thank you! It will be released tomorrow :)

**Comment by felipecrs** [comment]
@Danny89530 I'm receiving this issue in my logs after #270 released as 4.1.0:

```
ERROR[512]: loader.c:2524 load_modules: Error loading module 'res_resolver_unbound.so': libunbound.so.8: cannot open shared object file: No such file or directory
```

Is there a chance you can take a look?

**Comment by Danny89530** [comment]
Hi @felipecrs, I just performed the upgrade, and I just noticed that the "libunbound-dev" library is not installed on the container. I'm checking it right now...

**Comment by felipecrs** [comment]
Debian was also upgraded from 11 to 12, maybe it has something to do with it as well.

**Comment by Danny89530** [comment]
I have just tried to compile the Dockerfile separately, not considering the addon. Everything is compiled and installed as it should. Now I am compiling the addon, but I can't figure out why it would skip the installation of the library.

**Comment by Danny89530** [comment]
I'm having trouble understanding what the problem might be.
I just tried running the installation of the library separately, but it doesn't seem to be installed according to dpkg. Do you have any ideas?

<img width="1000" alt="immagine" src="https://github.com/TECH7Fox/asterisk-hass-addons/assets/3729455/6b5e2946-be15-4ae1-8708-c3f94dec70f6">

**Comment by Danny89530** [comment]
I'm having trouble understanding what the problem might be.
I just tried running the installation of the library separately using the apt command, but it doesn't seem to be installed according to dpkg. Do you have any ideas?

<img width="1102" alt="immagine" src="https://github.com/TECH7Fox/asterisk-hass-addons/assets/3729455/cba7ab9c-612f-4e4d-984e-1b6af1ed13d8">

**Comment by felipecrs** [comment]
Can you change to libunbound8 just to try?

I will take a closer look tomorrow otherwise.

**Comment by Danny89530** [comment]
Unfortunately, nothing has changed.
Even installing libunbound8 directly, it doesn't show up on dpkg during startup.
I am quite puzzled..

**Comment by felipecrs** [comment]
Oh, I know what's wrong. You added the dependency on the "build" docker layer. You should in fact add it to the "base" docker layer. Check the apt-get install command before the one you made changes to.

**Comment by felipecrs** [comment]
The build layer is intermediary and it's only used to build asterisk from source.

That's why you don't see the dependency after the build.

**Comment by felipecrs** [comment]
The build layer is intermediary and it's only used to build asterisk from source.

That's why you don't see the dependency after the build.

**Comment by felipecrs** [comment]
- #275 should fix this issue
