### ISSUE TITLE
Add TFTPD option

### ISSUE THREAD

**Issue by Danny89530** [TECH7Fox/asterisk-hass-addons#280]
Hello,
In these past few days, I've been working on the potential integration of a TFTP service within the addon, allowing users to enable or disable it through the configuration panel (disabled by default).

As I own Cisco devices, I realized the need to configure an external server for configuration uploads. However, the idea of having everything "at hand" seemed like the sensible approach.

After understanding the mistake in my last pull request, I conducted a significant number of tests (^^'). It appears that everything is functioning correctly. However, due to the nature of the UDP protocol, I'm encountering difficulties in reaching the container.

I'm wondering if it might be a good idea to integrate this service directly into the addon. In such a case, before submitting another potentially non-functional pull request, I would appreciate it if you could guide me on the requirements to set in the development environment to allow UDP traffic.

Thank you in advance,
DD

**Comment by felipecrs** [comment]
Can you elaborate on the relationship between TFTPD with Asterisk? I don't understand what one thing has to do with another.

**Comment by TECH7Fox** [comment]
Didn't asterisk also had a build-in tftp server for this?

**Comment by felipecrs** [comment]
@TECH7Fox on a quick look up I could not find anything like that. But maybe I didn't search correctly.

If there is no built-in TFTP server in Asterisk, then I would say your request is out of scope for this add-on.

If you want a TFTP server, you can create a standalone add-on for TFTPD. That's my recommendation.

But feel free to elaborate otherwise.

**Comment by TECH7Fox** [comment]
Also can't find it. Must have been freepbx then.

@Danny89530 if your just gonna use it once, I used tftpd64. Very easy to use and debug.

**Comment by Danny89530** [comment]
> Can you elaborate on the relationship between TFTPD with Asterisk? I don't understand what one thing has to do with another.

The relationship between TFTPD and Asterisk isn't directly intertwined, except for a specific use case involving various devices, such as Cisco phones. These devices require a TFTP server to facilitate functions like downloading license files, firmware updates, or even simple configuration files (for instance, in my case, I have Enterprise devices converted to 3PCC). One example specific to Cisco is the need for an XML configuration file.



In essence, the connection lies in the shared requirement of certain devices for a TFTP server to enable these essential functions.


> Also can't find it. Must have been freepbx then.
> 
> @Danny89530 if your just gonna use it once, I used tftpd64. Very easy to use and debug.

**Comment by Danny89530** [comment]
My intention was merely to put forward an idea; if you believe it's unnecessary, I can step back :).
Nonetheless, I would appreciate it if you could guide me on enabling the UDP protocol in the development environment.
I don't have much familiarity with VSCode and don't know how to adjust this setting..

**Comment by Danny89530** [comment]
Anyway, I have the changes published in a fork available here:
[https://github.com/Danny89530/asterisk-hass-addons](url)
Feel free to take a look if you'd like.

**Comment by felipecrs** [comment]
Honestly I don't use the development environment... I would recommend you try these changes outside of the development environment.

You can for example, build and push the image to ghcr.io or docker hub and then adjust the config.yaml:image key to point to your new image for testing. Or you can comment the image line in the config.yaml so that Home Assistant will build the dockerfile (I am imagining that you already have cloned this repo to /addons/).

**Comment by felipecrs** [comment]
> The relationship between TFTPD and Asterisk isn't directly intertwined, except for a specific use case involving various devices, such as Cisco phones. These devices require a TFTP server to facilitate functions like downloading license files, firmware updates, or even simple configuration files (for instance, in my case, I have Enterprise devices converted to 3PCC). One example specific to Cisco is the need for an XML configuration file.

Ok, thanks for explaining.

My suggestion for you is to build your own TFTPD add-on and share it with the community. I'm sure it will be useful for others.

Add-ons usually have a single purpose, and I believe TFTPD would make a great add-on.

https://developers.home-assistant.io/docs/add-ons/tutorial/

**Comment by felipecrs** [comment]
> Anyway, I have the changes published in a fork available here: https://github.com/Danny89530/asterisk-hass-addons Feel free to take a look if you'd like.

I checked it, things looks good. But if you make your own add-on you will be able to simplify a lot of things.
