### ISSUE TITLE
No audio when outside my LAN 

### ISSUE THREAD

**Issue by pbvdven** [TECH7Fox/asterisk-hass-addons#288]
Hi, im having the issue that i have no audio when im outside my LAN. TCP and UDP on LAN works fine. when i connect through tcp it will connect outside my LAN but then i have no audio at all when calling with udp no connection at all it works only inside LAN? also hass-sip card no audio outside lan. 

i got this error sometimes
WARNING[709][C-0000000a]: res_rtp_asterisk.c:3266 __rtp_recvfrom: PJ ICE Rx error status code: 70004 'Invalid value or argument (PJ_EINVAL)'.

any idea what im doing wrong 

thanks.

**Comment by pergolafabio** [comment]
make sure to open RTP ports too, its needed for audio

**Comment by felipecrs** [comment]
Most likely as @pergolafabio said. Let me know otherwise.
