### ISSUE TITLE
/config/asterisk/default/pjsip_custom.conf is purged at addon restart

### ISSUE THREAD

**Issue by Bram-diederik** [TECH7Fox/asterisk-hass-addons#293]
I try to make connection with my main asterisk system so that i can dail out using the sip card.

I think i need to make a trunk connection in /config/asterisk/default/pjsip_custom.conf  but this config file is purged every restart.

**Comment by felipecrs** [comment]
I think you did not read the docs: https://github.com/TECH7Fox/asterisk-hass-addons/blob/main/asterisk/DOCS.md#configuring-asterisk

**Comment by Bram-diederik** [comment]
```
o yeah i tried that also. did not know you are a fast closer. 
[core-ssh custom]$ ls
extentions.conf    pjsip_custom.conf


```

**Comment by felipecrs** [comment]
https://github.com/TECH7Fox/asterisk-hass-addons/issues/294
