### ISSUE TITLE
stuff from custom does not make it to default

### ISSUE THREAD

**Issue by Bram-diederik** [TECH7Fox/asterisk-hass-addons#294]
Hi, this code isnt making it to default. 

and I don't see the connection appearing in the integration. 

It i do things wrong can you give a working example please. I'm a example guy. 
and the manual is cutting it a bit short. 

```
[core-ssh custom]$ ls
extentions.conf    pjsip_custom.conf
[core-ssh custom]$ cat extentions.conf 
[default]
exten => _X.,1,Dial(PJSIP/sascha-trunk/${EXTEN})
[core-ssh custom]$ cat pjsip_custom.conf 
[karin]
type=endpoint
context=from-sascha
disallow=all
allow=opus
allow=ulaw
auth=karin
aors=karin
direct_media = no
rtp_symmetric = yes
force_rport = yes
allow=h263p
allow=h264
allow=vp8

[karin]
type=auth
auth_type=userpass
password=ikbenje<3je
username=karin

[karin]
type=auth
auth_type=userpass
password=bedenkmaariets
username=karin
```

**Comment by felipecrs** [comment]
> Hi, this code isnt making it to default.

Not sure what do you mean by that, but you can verify the content of the final file with:

```
docker exec -it addon_b35499aa_asterisk cat /etc/asterisk/pjsip_custom.conf
```

Using the Advanced SSH add-on with protection mode disabled.

There are some `pjsip_custom.conf` examples here: https://tech7fox.github.io/sip-hass-docs/docs/add-on/guides/doorbell

**Comment by Bram-diederik** [comment]
a that helps a lot. 
the content is shown and if i run asterisk -r the connection is shown but unavailable.

**Comment by felipecrs** [comment]
Meaning the custom config file is being read by Asterisk correctly, right?

**Comment by felipecrs** [comment]
I think you can also use `docker exec addon_b35499aa_asterisk asterisk -rx "pjsip show endopoints"` to display list of devices you set in pjsip_custom.

**Comment by Bram-diederik** [comment]
Yeah that worked. figuring out the connection.
asterisk is a beast for me to handle.  But i have the best low budget voicemail system in the world
