### ISSUE TITLE
Asterisk GUI

### ISSUE THREAD

**Issue by vlavrynovych** [TECH7Fox/asterisk-hass-addons#304]
Hi, 

This is definitely not an issue, it's a enhancement request 

Fist of all want to say that this addon is awesome and I was able to successfully run it. Thanks for the documentation. It helped a bit to me.

After I twiked a couple of the .conf files in my custom folder I found an http.conf. I turned it on and found only httpstatus page with the following information:
```
Asterisk™ HTTP Status
--
Server | Asterisk/20.5.2
Prefix | /asterisk
Bind Address | 192.168.1.50
Bind Port | 8088
SSL Bind Port | 8089
```

It's nice to know that it works, but by doing a quick research I found the Asterisk GUI and I wonder why shouldn't be pre-install in addon.

I am new to Asterisk and the only one reason why I was able to configure it for my needs is that I am a developer. Yes, it took for me a couple of hours to find docs, understand concepts and adopt to that weird syntax

I wish Asterisk addon to be more user friendly for wider usage in HA community and IMHO it have to has a GUI.

Link: http://www.asteriskdocs.org/en/2nd_Edition/asterisk-book-html-chunk/I_sect111_tt1363.html

Thanks again for your work on this project.

**Comment by TECH7Fox** [comment]
The asterisk-gui project seems to be dead. I believe the last version was from 2009.

There is FreePBX, which is a extension of Asterisk and provides a GUI, and I tried to implement that first as a add-on, but I got into too many problems. FreePBX has a lot of unnessary features enabled and the GUI is very buggy and sometimes shows config incorrectly. We can't maintain something like that in a add-on, while keeping it updated and as plug-and-play as we have now.

I like the idea, and if a lightweight asterisk-gui was still available I would implement it. But for now the HTTP server is only used for WS for the card.

You can however use the integration to get some live information from Asterisk.

I guess you could also find (or even create) a GUI that connects to the AMI. Also saw a Grafana plugin.

**Comment by vlavrynovych** [comment]
Hi guys, only today found your responses and can say that today my option is to use FreePBX as a separate instance on Proxmox VE. It works perfectly and doesn't require me to remember how to configure it. UI is simple as for me. For any person who will find this message I strongly recommend to use FreePBX.

But the addon is also good as a light weight solution or when you need to configure only once without reconfiguring each half a year. It was fun to play with it. I felt something like a nostalgia for the old times. The use of this addon pushed me to move forward

**Comment by felipecrs** [comment]
I personally find the FreePBX idea great, but I think it would be better off being a separate add-on.

Also, I wonder how does both compare regarding resources. If FreePBX doesn't add up too much, I think it's a great tradeoff.
