### ISSUE TITLE
rtsp-app not available on Pi builds

### ISSUE THREAD

**Issue by los93sol** [TECH7Fox/asterisk-hass-addons#311]
I'm trying to use rtsp-app to invoke an IP camera that has an rtsp stream, but does not support sip itself, but I get errors that rtsp-sip does not exist on the extension.

I found the following that looks like it may be getting excluded in the build https://github.com/TECH7Fox/asterisk-hass-addons/blob/d93fffdf5c8bf5c8b070d97b845e1958d518d8df/asterisk/Dockerfile#L134

**Comment by felipecrs** [comment]
Oh God. You are right.

**Comment by los93sol** [comment]
I did find where @TECH7Fox mentioned this on Home Assistant forums and referenced a GitHub issue for it as well.  It looks like a workaround has been provided https://github.com/tommyjlong/app_rtsp_sip/issues/5#issuecomment-1229562427

**Comment by felipecrs** [comment]
I don't know why we do that, so let's try building it: https://github.com/TECH7Fox/asterisk-hass-addons/pull/312

**Comment by felipecrs** [comment]
> I did find where @TECH7Fox mentioned this on Home Assistant forums and referenced a GitHub issue for it as well. It looks like a workaround has been provided [tommyjlong/app_rtsp_sip#5 (comment)](https://github.com/tommyjlong/app_rtsp_sip/issues/5#issuecomment-1229562427)

Great! If compilation fails we know what to do then.

**Comment by felipecrs** [comment]
@los93sol when you get a chance please let us know whether it worked or not.

**Comment by los93sol** [comment]
Thanks for getting it in so quick!  It looks like it did work, but my camera only supports RTSP and I get an error when it tries to load the feed from app_rtsp_sip so I assume it’s working but my camera isn’t compatible

**Comment by felipecrs** [comment]
I see. Well I never used it so I don't know how to help too. But thanks for the feedback!

**Comment by tommyjlong** [comment]
> Thanks for getting it in so quick! It looks like it did work, but my camera only supports RTSP and I get an error when it tries to load the feed from app_rtsp_sip so I assume it’s working but my camera isn’t compatible

What is the error?

**Comment by los93sol** [comment]
[Mar 20 13:41:13]   == Endpoint 100 is now Reachable
[Mar 20 13:41:28]     -- Executing [666@default:1] Answer("PJSIP/100-00000000", "") in new stack
[Mar 20 13:41:29]     -- Executing [666@default:2] Wait("PJSIP/100-00000000", "1") in new stack
[Mar 20 13:41:30]     -- Executing [666@default:3] RTSP-SIP("PJSIP/100-00000000", "rtsp://userRedacted:passwordRedacted@192.168.10.27:554/h264Preview_01_main") in new stack
[Mar 20 13:41:30] NOTICE[617][C-00000001]: app_rtsp_sip.c:2434 main_loop: >rtsp-sip main loop
[Mar 20 13:41:30] ERROR[617][C-00000001]: app_rtsp_sip.c:2341 RecvResponse: Error receiving response [0,0].Success
[Mar 20 13:41:30] NOTICE[617][C-00000001]: app_rtsp_sip.c:3839 main_loop: <rtsp-sip main loop
[Mar 20 13:41:30]     -- Executing [666@default:4] Wait("PJSIP/100-00000000", "10") in new stack
[Mar 20 13:41:40]     -- Executing [666@default:5] Hangup("PJSIP/100-00000000", "") in new stack
[Mar 20 13:41:40]   == Spawn extension (default, 666, 5) exited non-zero on 'PJSIP/100-00000000'

**Comment by tommyjlong** [comment]
@los93sol 
Not much to go on, other than it received something from the camera with 0 length.
Couple of things to try:

1. in your Asterisk config where you make a call to the camera, since you're not using SIP, add a `,0` at the end. Something like:
   `same = n,RTSP-SIP(rtsp://userRedacted:passwordRedacted@192.168.10.27:554/h264Preview_01_main,0)`
2. Increase the Log level to get more details.
