### ISSUE TITLE
ARM support for app_rtsp_sip

### ISSUE THREAD

**Issue by tommyjlong** [TECH7Fox/asterisk-hass-addons#313]
Hi @felipecrs 
I see you just added a patch to include a couple of `#defines` for the `app_rtsp_sip.c` for ARM based builds.
Just checking in to see if these built OK.
 
A couple of things too:
[Here](https://github.com/tommyjlong/app_rtsp_sip/issues/5#issuecomment-1225018728) it was mentioned that the builds failed on:
aarch64, armhf and armv7
but looks like the build dependency is `arm*`; maybe need to add aarch64?

When I was working on this problem back in 2022, I also added a third `#define`
`#define ARM`
I'm not sure why, but if the arm architectures build without it, then probably OK to leave it out.

**Comment by felipecrs** [comment]
The compilation worked fine for all the three ARM platforms, but I did not test yet.

**Comment by felipecrs** [comment]
Btw TARGETARCH should be arm64 rather than aarch64, so it should work.

**Comment by tommyjlong** [comment]
Good to hear!

**Comment by felipecrs** [comment]
v5.0.0 to be released soon should include it, btw I'm dropping support for armhf (https://github.com/TECH7Fox/asterisk-hass-addons/pull/314), please chime in if you have any concern.
