### ISSUE TITLE
Use `friendly_name` instead of `id` as the caller id

### ISSUE THREAD

**Issue by OnFreund** [TECH7Fox/asterisk-hass-addons#321]
The `friendly_name` attribute should have the person's name, whereas `id` can be random id.
https://github.com/TECH7Fox/asterisk-hass-addons/blob/d6b270dc76071ba494eaba443e9d11579ea4ba64/asterisk/rootfs/etc/cont-init.d/asterisk.sh#L148

**Comment by felipecrs** [comment]
PR is welcome, @OnFreund.

**Comment by OnFreund** [comment]
There you go: #322

**Comment by felipecrs** [comment]
#322
