### ISSUE TITLE
Error when upgrading to latest version

### ISSUE THREAD

**Issue by hoanglongutc** [TECH7Fox/asterisk-hass-addons#334]
I'm getting this error when upgrading to the latest version, I've tried uninstalling and reinstalling but the same error still appears.

`Can't install ghcr.io/tech7fox/asterisk-hass-addon:4.3.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.3.0&fromImage=ghcr.io%2Ftech7fox%2Fasterisk-hass-addon&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

**Comment by sesardelaisla** [comment]
+1

> I'm getting this error when upgrading to the latest version, I've tried uninstalling and reinstalling but the same error still appears.
> 
> `Can't install ghcr.io/tech7fox/asterisk-hass-addon:4.3.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.3.0&fromImage=ghcr.io%2Ftech7fox%2Fasterisk-hass-addon&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

**Comment by felipecrs** [comment]
Should work now.
