### ISSUE TITLE
Stop using `host_network: true`

### ISSUE THREAD

**Issue by pergolafabio** [TECH7Fox/asterisk-hass-addons#44]
I prefer to have this mode only as a temp workaround, I think it can have conflict with other addons? If there are other common ports used?

Or maybe make this mode an option that can be turned off by users? So users can open ports they need..

I had call drops on softphones though after 32 sec, when this mode was disabled... This is a common issue... Maybe it was because of the RTP ports, there were only 8 configured, maybe we do need more? Or the custom range was not configured properly?

I want to investigate this again, would be great if I could turn off host again and test with custom ranges....

Maybe something for later?

Thnx

**Comment by felipecrs** [comment]
> Or maybe make this mode an option that can be turned off by users? So users can open ports they need..

Not possible currently.

**Comment by felipecrs** [comment]
I totally agree that we should move away from host network, but I think we should wait for https://community.home-assistant.io/t/add-support-for-port-ranges-in-add-on-config-yaml/375695/5.

We can also think about implementing it in HA by ourselves, and send them a PR.

**Comment by nanosonde** [comment]
Are you really sure that you want to remove the host network feature in the future?
I recommend on reading about things like:
Double NAT and SIP
Without using the host network you will introduce another NAT at docker networking.

As most people at home have the usual IPv4 LAN behind home router doing NAT, it will be required that those routers are ALGs and are SIP-aware. If they support it, then modifing SIP packets internal IP adresses will happen and everything is fine.
If not, things will not work properly.

**Comment by nanosonde** [comment]
I think it is also time for the HA project as a whole to move on and also support IPv6 properly.
Of couse this will cause other issues as changing dynamic IPv6 prefixes from ISP.
However, this should be doable.
So we can - at some day - get rid of all these bad old things like NAT.

**Comment by pergolafabio** [comment]
Pls, don't remove it :-)

**Comment by nanosonde** [comment]
I would recommend to limit the port range in rtp.conf.

Currently asterisk could choose from 10000-20000. IMHO this is way too much for just a simple intercom setup.

WebRTC muxes RTP and RTCP onto one port.
Normal clients could also use dedicated ports for each.

So I would assume that something like 100 UDP ports should be enough if asterisk also does the media bridging with direct_media=no.

**Comment by felipecrs** [comment]
I would doubt there would be any issue with the setup unless by the port range configuration. But it's not worth it to argue, as HA does not support port range anyway.
