### ISSUE TITLE
Add fail2ban & iptables

### ISSUE THREAD

**Issue by pergolafabio** [TECH7Fox/asterisk-hass-addons#51]
Can you add those and make it configurable? It's to protect our PBX from outside

**Comment by felipecrs** [comment]
In the freepbx docker image, fail2ban requires --privileged, which is very discouraged in add-ons and would require a manual step in the installation. Not to mention it would decrease the score of the add-on in overall to 1, I think.

**Comment by pergolafabio** [comment]
Yeah , but protecting an local hosted app is also important, so I dont care about score :-)

**Comment by Tekno-man** [comment]
> In the freepbx docker image,

Is this also the case with asterisk rather than FreePBX?

**Comment by felipecrs** [comment]
I think that if we manage to make https://github.com/TECH7Fox/Asterisk-add-on/issues/56 work, we won't need to have any port exposed outside.

**Comment by felipecrs** [comment]
@pergolafabio I think the best thing that can be done is to leverage fail2ban from Home Assistant for the job, as in #178. I'm closing this issue in favor of #178, but if you disagree we can reopen.
